### ISSUE TITLE
nacos相关配置项中包含placeholder未被解析

### ISSUE THREAD

**Issue by pingguoilove** [nacos-group/nacos-spring-boot-project#245]
例如
```
config:
   group: test-group
nacos:
  config:
     data-id:xxxxxx
     group: ${config.group}
```
在启动的时候，nacos的group属性将不会被解析，直接取了``${config.group}``。原因应该是``com.alibaba.boot.nacos.config.util.AttributeExtractTask#calculate``方法中，在解析值的时候没有考虑``placeholder``
