### ISSUE TITLE
client error: invalid param. null错误

### ISSUE THREAD

**Issue by Skqing** [nacos-group/nacos-spring-boot-project#25]
配置信息
```
nacos:
  config:
    server-addr: 192.168.31.82:8848
    namespace: a698a979-b73e-4417-8c3d-f12c02509c30
```

错误信息
```
2019-05-20 16:26:58.258 ERROR 5936 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

client error: invalid param. null

Action:

please check your client configuration
```

调试看到的错误信息
```
java.lang.RuntimeException: ConfigService can't be created with dataId :datasource.properties , groupId : DEFAULT_GROUP , properties : {encode=UTF-8}
```
