### ISSUE TITLE
nacos 在springboot无法获取到配置

### ISSUE THREAD

**Issue by suiyueqiannian** [nacos-group/nacos-spring-boot-project#292]
配置如下：
```
nacos:
  config:
    bootstrap:
      enable: true
      log-enable: true
    server-addr: "http://internal-k8s-xx-xx.elb.amazonaws.com.cn/nacos"
    data-id: fsm-dispatch
    group: fsm
    type: yaml
    auto-refresh: true
    namespace: '@profiles.active@'
    password: 'nacos'
    username: 'nacos'
    max-retry: 10
```

同时使用
```
@NacosValue("${dubbo.registry.address}")
	private String address;
```

pom.xml 引入
```
<dependency>
			<groupId>com.alibaba.boot</groupId>
			<artifactId>nacos-config-spring-boot-starter</artifactId>
			<version>0.2.12</version>
		</dependency>
```

最终报错，Could not resolve placeholder 'dubbo.registry.address' in value "${dubbo.registry.address}"
