### ISSUE TITLE
Springboot集成Nacos配置中心报错

### ISSUE THREAD

**Issue by shining-stars-lk** [nacos-group/nacos-spring-boot-project#328]
## 版本
- SpringBoot：2.5.2
- Nacos：0.2.5
## 引入的Nacos依赖：
```xml
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-config-spring-boot-starter</artifactId>
    <version>0.2.5</version>
</dependency>
```
## 读取的相关配置
```yaml
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: xxx:8848
    data-id: web-mdt.yaml
    namespace: xxx
    group: mdt_group
    type: yaml
    auto-refresh: true
    username: nacos
    password: nacos
    ext-config:
      - server-addr: xxx:8848
        data-id: web-mdt-company.yaml
        namespace: xxx
        group: mdt_group
        type: yaml
        auto-refresh: true
        username: nacos
        password: nacos
```
## 出现的错误
在项目启动时，出现了类找不到错误
```
web- 2024-04-07 13:51:15 [restartedMain] ERROR
                o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nacosConfigurationPropertiesBinder': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.boot.nacos.config.binder.NacosBootConfigurationPropertiesBinder]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/ConfigurationBeanFactoryMetadata
```
这是什么原因？
