### ISSUE TITLE
spring boot 2.7.15通过application.yml配置nacos.config.*不生效

### ISSUE THREAD

**Issue by xishian** [nacos-group/nacos-spring-boot-project#332]
启动类
```@EnableScheduling
@SpringBootApplication
@NacosPropertySource(dataId = "${spring.application.name}", autoRefreshed = true)
public class MyApplication {

    public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }
}
```

配置文件application.yml

```
nacos:
  config:
    server-addr: 10.47.181.20:8848
    group: DEV_GROUP
```
这里配置的group是不会生效的，还是用的默认值DEFAULT_GROUP
> 如果这是预期的行为，建议从NacosConfigProperties中移除这些不会生效的配置项
